language: ruby

sudo: false

rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head

bundler_args: --without development --binstubs

script:
  - export COVERAGE=true
  - rubocop
  - reek lib/
  - cane
  - bundle exec rake test_with_coveralls
