require_relative 'match_product_helper'

module Rules
  # The TwoForOne rule generates a discount everytime the basket contains a
  # pair of items of a certain product
  class TwoForOne
    include MatchProductHelper

    # @param product [Product]
    def initialize(product)
      @product = product
    end

    # Executes the rule on a basket
    # @param [Basket] basket
    # @return [Event] the event generated by the matching products. Otherwise
    #   return nil
    def fire_for(basket)
      num = num_matching_products(basket)
      Event.new(created_by: self,
                product: @product,
                num_matches: num / 2,
                new_price: Price.zero) if num > 1
    end
  end
end
