# The Event class represents an event generated by a rule fired
class Event
  attr_reader :created_by, :product, :num_matches, :new_price

  def initialize(args)
    @created_by = args[:created_by]
    @product = args[:product]
    @num_matches = args[:num_matches]
    @new_price = args[:new_price]
  end

  # @return [Price] the total discount related to this event generated by a
  #   pricing rule
  def discount
    Price.new(discount_per_unit * num_matches)
  end

  private

  # @return [Fixnum] The value
  def discount_per_unit
    product.price.value - new_price.value
  end
end
